#数据库设置
#千万注意不能用data-username: 会导致连接错误
spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssmbuild?useSSL=false&useUnicode=true&characterEncoding=utf8
    data-username:

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp




#整合mybatis
mybatis:
  type-aliases-package: com.hang.springboot_end.domain
  mapper-locations: classpath:com/hang/springboot_end/dao/*.xml





